### ISSUE TITLE
Model checkpoints

### ISSUE THREAD

**Issue by chricro** [SHI-Labs/CuMo#10]
Hi!

Thank you for your work, @chrisjuniorli. I'd like to fine-tune the shi-labs/CuMo-mistral-7b model for my particular use case.

I noticed that the script `scripts/cumo/mistral_7b/sft_mistral_7b.sh` includes the argument `--pretrain_mm_mlp_adapter $CuMo_DIR/checkpoints/cumo-mistral-7b-pft/mm_projector.bin`, but the mm_projector weights are not saved on huggingface.  

Could you provide the weights for the mm_projector to bypass the pretraining and pft steps?

**Comment by chrisjuniorli** [comment]
Hi, we released checkpoints at https://huggingface.co/shi-labs/CuMo-misc for you to bypass these stages.

**Comment by chricro** [comment]
Hi @chrisjuniorli, thanks for pointing that out, it's helpful!
