### ISSUE TITLE
power usage is low.

### ISSUE THREAD

**Issue by Marcovaldon** [SHI-Labs/CuMo#11]
我将deepspeed改成了2，power usage也没有看到多少提升，多个节点训练的时候power usage只有150左右。请问有什么加速方法吗，谢谢。

**Comment by chrisjuniorli** [comment]
Hi, we didn't meet this issue before, which gpu or clusters you used for training, and which type of multi-node training framework you used

**Comment by Marcovaldon** [comment]
A100(80G)    deepspeed zero2
