### ISSUE TITLE
[Question] Paper table2 miss some baselines

### ISSUE THREAD

**Issue by pkumc** [SHI-Labs/CuMo#13]
@chrisjuniorli Really appreciate your work! I have some questions about the results of table2. To evaluate the effectiveness of the co-upcycled MoE blocks, other parts in the model should be same. So it seems that **LLaVA-v1.5-Vicuna-7B VS CuMo-Vicuna-7B** or **LLaVA-v1.5-Mistral-7B VS CuMo-Mistral-7B** should be fair. But table2 is **LLaVA-v1.5-Vicuna-7B VS CuMo-Mistral-7B**. Mistral-7B itself is better than Vicuna-7B. Why not keep the same LLM backbone?

**Comment by chrisjuniorli** [comment]
Hi @pkumc , Thanks for your insterets in our work! 
We do have a LLaVA-v1.5-Mistral-7B baseline in Table 3. Our intention was to use Table 3/4 to show the effectiveness of the co-upcycled MoE blocks. Table 2 is more like Table 1, which is to compare performance with other models under the same training data, but we do understand your concern here and may update the Table 2 with an added row on  LLaVA-v1.5-Mistral-7B. Thanks!
