### ISSUE TITLE
What the size of the input image should be of CuMo?

### ISSUE THREAD

**Issue by junleiz** [SHI-Labs/CuMo#2]

**Comment by chrisjuniorli** [comment]
the input image can be any size and the data loader will resize it to 336x336 and then send it to CLIP.

**Comment by junleiz** [comment]
Thanks.

**Comment by junleiz** [comment]
![image](https://github.com/SHI-Labs/CuMo/assets/26025961/9a9248d7-1fe0-4a47-8887-46d161d80f55)
Hello， I noticed that in paper you implement the multi-resolution input. Does this implement have this feature? Thanks!

**Comment by chrisjuniorli** [comment]
Yes, check the https://github.com/SHI-Labs/CuMo/blob/main/cumo/model/multimodal_encoder/clip_encoder.py for the implementation details.

**Comment by junleiz** [comment]
Thanks!
