### ISSUE TITLE
Train the model without Deepspeed ZeRO

### ISSUE THREAD

**Issue by moshiiur** [SHI-Labs/CuMo#5]
Hi, 
As you have mentioned how we can use Deepspeed multi-node trainings to train the model on multiple nodes. I was curious if we can train the model without incorporating them at all? 

https://github.com/SHI-Labs/CuMo/blob/main/docs/getting_started.md
![image](https://github.com/SHI-Labs/CuMo/assets/62719277/bdc7e08f-6778-4227-af01-aee0fea5eb3b)

**Comment by chrisjuniorli** [comment]
Hi, you mean training the model with another multi-node framework or without deepspeed at all even for single-node

**Comment by moshiiur** [comment]
Without deepspeed at all even for single-node.

**Comment by chrisjuniorli** [comment]
for now we've only tried training the model with deepspeed. If you prefer to use other frameworks or vanilla pytorch, you may explore other llava implementations without deepspeed, like https://github.com/alibaba/Pai-Megatron-Patch, which should be compatible with CuMo.
